language: rust
os:
- linux
- osx
rust:
- nightly
- beta
- stable
script:
- cargo build
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo update -Z minimal-versions; fi
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo build; fi
branches:
  only:
    master
