language: rust
sudo: false
os:
- linux
- osx
rust:
- nightly
- beta
- stable
script:
- cargo build
branches:
  only:
    master
after_success: |
  [ $TRAVIS_PULL_REQUEST == "false" ] &&
  [ $TRAVIS_RUST_VERSION == "stable" ] &&
  [ $TRAVIS_OS_NAME == "linux" ] &&
  bash ./publish-docs.sh
