[package]
name = "c-types"
license = "MIT"
version = "0.1.3"
authors = ["David Hotham"]
description = """
Re-exports of cross-platform types, gathered from libc and winapi
"""
homepage = "https://github.com/dimbleby/rust-c-types"
repository = "https://github.com/dimbleby/rust-c-types"
documentation = "http://dimbleby.github.io/rust-c-types"
readme = "README.md"
keywords = ["libc", "winapi"]

[target.'cfg(unix)'.dependencies]
libc = "0.2.10"

[target.'cfg(windows)'.dependencies]
winapi = "0.2.6"
